-- AlterTable
ALTER TABLE "warehouse"."treatment_goal_outcomes" ALTER COLUMN "estimate_appt_count" DROP NOT NULL,
ALTER COLUMN "current_appt_count" DROP NOT NULL,
ALTER COLUMN "discharged_appt_count" DROP NOT NULL,
ALTER COLUMN "goal_timeframe_interval" DROP NOT NULL,
ALTER COLUMN "goal_timeframe_id" DROP NOT NULL,
ALTER COLUMN "goal_timeframe_id" SET DEFAULT 0,
ALTER COLUMN "goal_achieved_ind" DROP NOT NULL,
ALTER COLUMN "goal_deleted_ind" DROP NOT NULL,
ALTER COLUMN "discharged_outcome_id" DROP NOT NULL,
ALTER COLUMN "discharged_outcome_id" SET DEFAULT 0,
ALTER COLUMN "estimate_journey_days" DROP NOT NULL,
ALTER COLUMN "actual_journey_days" DROP NOT NULL,
ALTER COLUMN "year_goal_started" DROP NOT NULL,
ALTER COLUMN "quarter_goal_started" DROP NOT NULL,
ALTER COLUMN "month_goal_started" DROP NOT NULL,
ALTER COLUMN "week_goal_started" DROP NOT NULL,
ALTER COLUMN "email_out_events" DROP NOT NULL,
ALTER COLUMN "message_out_events" DROP NOT NULL;
