-- AlterTable
ALTER TABLE "practice"."provider_appointments" ALTER COLUMN "import_id" SET DATA TYPE BIGINT,
ALTER COLUMN "related_id" SET DATA TYPE BIGINT,
ALTER COLUMN "recurrence_id" SET DATA TYPE BIGINT,
ALTER COLUMN "room_id" SET DATA TYPE BIGINT,
ALTER COLUMN "provider_id" SET DATA TYPE BIGINT,
ALTER COLUMN "owner_id" SET DATA TYPE BIGINT,
ALTER COLUMN "site_id" SET DATA TYPE BIGINT,
ALTER COLUMN "vendor_id" SET DATA TYPE BIGINT;
