-- AlterTable
ALTER TABLE "drmg"."decision_log" ALTER COLUMN "date_decided" DROP NOT NULL,
ALTER COLUMN "date_execute_started" DROP NOT NULL,
ALTER COLUMN "date_execute_ended" DROP NOT NULL,
ALTER COLUMN "constraints" DROP NOT NULL,
ALTER COLUMN "stakeholders" DROP NOT NULL,
ALTER COLUMN "information_sources" DROP NOT NULL,
ALTER COLUMN "available_options" DROP NOT NULL,
ALTER COLUMN "chosen_option" DROP NOT NULL,
ALTER COLUMN "reasoning" DROP NOT NULL,
ALTER COLUMN "risk_level" DROP NOT NULL,
ALTER COLUMN "risk_summary" DROP NOT NULL,
ALTER COLUMN "negative_side_effects" DROP NOT NULL,
ALTER COLUMN "probability_of_failure" DROP NOT NULL,
ALTER COLUMN "positive_side_effects" DROP NOT NULL,
ALTER COLUMN "probability_of_success" DROP NOT NULL,
ALTER COLUMN "probability_of_success" SET DEFAULT 0,
ALTER COLUMN "decision_makers" DROP NOT NULL,
ALTER COLUMN "confidence_level" DROP NOT NULL,
ALTER COLUMN "reverse_strategy" DROP NOT NULL,
ALTER COLUMN "outcome_results" DROP NOT NULL,
ALTER COLUMN "outcomes_vs_expectations_review" DROP NOT NULL,
ALTER COLUMN "outcome_lessons_learned" DROP NOT NULL,
ALTER COLUMN "date_outcome_reviewed" DROP NOT NULL;
