-- AlterTable
ALTER TABLE "warehouse"."treatment_goal_outcomes" ALTER COLUMN "condition_problems" DROP NOT NULL,
ALTER COLUMN "discharged_condition_problems" DROP NOT NULL,
ALTER COLUMN "goal_details" DROP NOT NULL,
ALTER COLUMN "goal_activity" DROP NOT NULL,
ALTER COLUMN "goal_activity_details" DROP NOT NULL,
ALTER COLUMN "goal_timeframe" DROP NOT NULL,
ALTER COLUMN "discharged_outcome_type" DROP NOT NULL,
ALTER COLUMN "discharged_outcome_details" DROP NOT NULL,
ALTER COLUMN "goal_notes" DROP NOT NULL,
ALTER COLUMN "goal_plan_notes" DROP NOT NULL,
ALTER COLUMN "goal_mid_notes" DROP NOT NULL,
ALTER COLUMN "goal_final_notes" DROP NOT NULL,
ALTER COLUMN "goal_non_completion_notes" DROP NOT NULL,
ALTER COLUMN "followup_notes" DROP NOT NULL;
