-- AlterTable
ALTER TABLE "practice"."clients" ALTER COLUMN "employer_id" SET DEFAULT -1,
ALTER COLUMN "employer_name" SET DEFAULT 'Unknown',
ALTER COLUMN "why_choose_us_id" SET DEFAULT -1,
ALTER COLUMN "why_choose_us" SET DEFAULT 'Unknown',
ALTER COLUMN "referral_source_id" SET DEFAULT -1,
ALTER COLUMN "referral_source" SET DEFAULT 'Unknown',
ALTER COLUMN "referred_by_type" SET DEFAULT 'Unknown',
ALTER COLUMN "referred_by_id" SET DEFAULT -1,
ALTER COLUMN "medical_centre_id" SET DEFAULT -1,
ALTER COLUMN "medical_centre" SET DEFAULT 'Unknown',
ALTER COLUMN "gp_id" SET DEFAULT -1,
ALTER COLUMN "gp_name" SET DEFAULT 'Unknown',
ALTER COLUMN "occupation_id" SET DEFAULT -1,
ALTER COLUMN "occupation_name" SET DEFAULT 'Unknown',
ALTER COLUMN "health_insurer" SET DEFAULT 'Unknown',
ALTER COLUMN "work_intensity_id" SET DEFAULT -1,
ALTER COLUMN "work_intensity_name" SET DEFAULT 'Unknown',
ALTER COLUMN "ethnic_group_id" SET DEFAULT -1,
ALTER COLUMN "ethnic_group_name" SET DEFAULT 'Unknown';
